# Generated by Django 5.0.2 on 2024-03-01 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MainCooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MainDVD_drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MainHdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MainHeadset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MainKeyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MainMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MainMotherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MainMouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MainOc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MainPower_supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MainProcessors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48, verbose_name='Тип процессора')),
            ],
        ),
        migrations.CreateModel(
            name='MainRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='MainSound_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MainSsd1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MainSsd2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MainVideoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainWifi_adapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='my_site.mainhdd')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleCooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('cooling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooling', to='my_site.maincooling')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleDVD_drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('dvd_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dvd_drive', to='my_site.maindvd_drive')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleHdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('hdd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hdd', to='my_site.mainhdd')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleHeadset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('headset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headset', to='my_site.mainheadset')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleKeyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyboard', to='my_site.mainkeyboard')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor', to='my_site.mainmonitor')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleMotherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard', to='my_site.mainmotherboard')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleMouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouse', to='my_site.mainmouse')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleOc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('oc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oc', to='my_site.mainoc')),
            ],
        ),
        migrations.CreateModel(
            name='SimplePower_supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('power_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_supply', to='my_site.mainpower_supply')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleProcessors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('processors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processors', to='my_site.mainprocessors')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='images/')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ram', to='my_site.mainram')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleSound_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('sound_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_card', to='my_site.mainsound_card')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleSsd1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('ssd1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssd1', to='my_site.mainssd1')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleSsd2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('ssd2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssd2', to='my_site.mainssd2')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleVideoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('video_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_card', to='my_site.mainvideocard')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleWifi_adapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('wifi_adapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifi_adapter', to='my_site.mainwifi_adapter')),
            ],
        ),
    ]
