# Generated by Django 5.0.2 on 2024-03-01 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='simplecase',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simplecooling',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simpledvd_drive',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simplehdd',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simpleheadset',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simplekeyboard',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simplemonitor',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simplemotherboard',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simplemouse',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simpleoc',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simplepower_supply',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simpleprocessors',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simpleram',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simplesound_card',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simplessd1',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simplessd2',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simplevideocard',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simplewifi_adapter',
            name='summ',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('summ', models.IntegerField(default=0)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='my_site.userprofile')),
            ],
        ),
    ]
