# Generated by Django 5.0.2 on 2024-03-02 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_userprofile_simplecase_summ_simplecooling_summ_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainMotherboard',
            new_name='MainMother_board',
        ),
        migrations.CreateModel(
            name='SimpleMother_board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('summ', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='images/')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_board', to='my_site.mainmother_board')),
            ],
        ),
        migrations.DeleteModel(
            name='SimpleMotherboard',
        ),
    ]
