# Generated by Django 5.0.2 on 2024-03-02 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_rename_mainmotherboard_mainmother_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplecase',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='my_site.maincase'),
        ),
    ]
